### ISSUE TITLE
Course Completion Certificate

### ISSUE THREAD

**Issue by linuxtek-canada** [ModernAppsNinja/vspheretanzu101_vt7301#531] opened 2021-06-05 22:05 UTC
Went through this process, and have 100% in all of the tests.  

I believe it generated a badge on Badgr but when I go to my homepage like in the video, I don't see the vSphere with Tanzu 101 course show up.  If I click on "Certs" I get a 404 error:

https://modernappsninjas.github.io/linuxtek-canada/

This link I believe has a typo to https://modernappsninjas.github.io/linuxtek-canada/cert instead of https://modernappsninjas.github.io/linuxtek-canada/certs

But I still don't see the course completion show up, and I can't resubmit it.

**Comment by afewell** [comment] 2021-06-09 05:52
Ok this is fixed now, thanks for your engagement and feedback, good connecting with you at the VMUG event as well. 

In case your interested, this is caused by a flaw in my distributed workflow design that created race conditions, essentially a lot of workflows modify repository files and each time files on a repo are modified it triggers a workflow to run a hugo build to generate and push updated html via github pages to your member site webpage. And when too many changes happen too quickly, the workflow will sometimes fail. The html is generated from the github backend, and the backend is completely stable so what would happen naturally is the next time you enrolled in a course or did anything else that modified a file on your member page repo it would trigger another build and it would fix itself. 

The simplest workaround until this is fixed if you run into it again, do please open an issue ticket as the fix is sort of manual until I make a better one ... but, you can always verify everything is working by looking at the github backend. I set it up so that a higher level grade report that only shows the overall percent correct/failed on the test is displayed on the member webpage, and those files are in the content/english/docs/course directory for courses you enrolled in but havent finished yet, and in the content/english/docs/cert directory for courses you have completed, the file named _coursename_.md in the cert directory will have your openbadge id and link to your verification page. At the same time, its probably easier to check if the cert provisioning worked by logging into your badgr account, if you setup a free badgr account with the same email address you used when you registered, the new badge should show up I think pretty much right away after the course completion workflow runs. 

Also there are more detailed grade reports that show the result for each question individually in the static/userdata/courses/_coursename_/ directory. 

I cant think of an ideal super-quick fix for the problem, the a reasonably ok fix isnt tons of work but its a good bit and may take me a bit. Ultimately we just need clear sets of rules and some policies to ensure workflows dont conflict. I will try to get to it as soon as I can and will share all the details and make it a collaborative project to observe and/or participate. 

Thanks!

**Closed by afewell** 2021-06-09 05:52 UTC
Labels: area/modernappsninjas, kind/bug
